// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3vN8qhnGhZ6KhS2vZo-nl_tCzvLu0Cqo',
    appId: '1:333990642707:web:41a6697a1024d835006be6',
    messagingSenderId: '333990642707',
    projectId: 'movies-9c079',
    authDomain: 'movies-9c079.firebaseapp.com',
    storageBucket: 'movies-9c079.firebasestorage.app',
    measurementId: 'G-7KVL7BH3XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgRFajoKycc3-CnAwWklpHDEpys0x8JAc',
    appId: '1:333990642707:android:d9e8950996b44e2c006be6',
    messagingSenderId: '333990642707',
    projectId: 'movies-9c079',
    storageBucket: 'movies-9c079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoIoBLyAGUgtNeAP3vQHr16IjHbYdVGho',
    appId: '1:333990642707:ios:7f6e37f5ed671064006be6',
    messagingSenderId: '333990642707',
    projectId: 'movies-9c079',
    storageBucket: 'movies-9c079.firebasestorage.app',
    iosClientId: '333990642707-7g5lrm5l5ij6p4f71rjjgs265hn7c3t1.apps.googleusercontent.com',
    iosBundleId: 'com.movies.movies',
  );

}